"""add agent_runs and agent_messages tables

Revision ID: 24b27c0794be
Revises: 3a6129bed017
Create Date: 2026-07-25 04:32:17.987299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b27c0794be'
down_revision: Union[str, Sequence[str], None] = '3a6129bed017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_incident_id'), 'agent_runs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_run_id'), 'agent_messages', ['run_id'], unique=False)
    # SQLite can't ALTER a table to add a foreign key constraint directly -
    # batch mode does it via SQLAlchemy's copy-and-move strategy, which also
    # works fine on Postgres, so this one path covers both dialects.
    with op.batch_alter_table('proposed_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_run_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_proposed_actions_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_foreign_key('fk_proposed_actions_agent_run_id', 'agent_runs', ['agent_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposed_actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_proposed_actions_agent_run_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_proposed_actions_agent_run_id'))
        batch_op.drop_column('agent_run_id')
    op.drop_index(op.f('ix_agent_messages_run_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_incident_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
