"""add embeddings table

Revision ID: 57b6013fc24d
Revises: 94500dea0c34
Create Date: 2026-07-25 01:40:41.698910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db_models


# revision identifiers, used by Alembic.
revision: str = '57b6013fc24d'
down_revision: Union[str, Sequence[str], None] = '94500dea0c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite has no vector extension at all - EmbeddingVector falls back to
    # a plain Text column there (see db_models.py), so this is only needed
    # (and only valid syntax) on Postgres.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vector', app.db_models.EmbeddingVector(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_content_id'), 'embeddings', ['content_id'], unique=False)
    op.create_index(op.f('ix_embeddings_content_type'), 'embeddings', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_content_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_content_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
