"""add correlation_claim and case-insensitive asset host index

Revision ID: 94500dea0c34
Revises: d28819af638b
Create Date: 2026-07-24 22:57:54.959278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94500dea0c34'
down_revision: Union[str, Sequence[str], None] = 'd28819af638b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_host'), table_name='assets')
    op.create_index(op.f('ix_assets_host'), 'assets', ['host'], unique=False)
    op.add_column('events', sa.Column('correlation_claim', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_events_correlation_claim'), 'events', ['correlation_claim'], unique=False)
    # ### end Alembic commands ###

    # Manual: SQLite's reflection can't detect expression-based indexes, so
    # autogenerate can't diff this one - added by hand instead.
    op.create_index('ix_assets_host_lower', 'assets', [sa.text('lower(host)')], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_assets_host_lower', table_name='assets')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_correlation_claim'), table_name='events')
    op.drop_column('events', 'correlation_claim')
    op.drop_index(op.f('ix_assets_host'), table_name='assets')
    op.create_index(op.f('ix_assets_host'), 'assets', ['host'], unique=1)
    # ### end Alembic commands ###
