"""add connector and response action instance tables, executed state on proposed actions

Revision ID: a2ad6aa0d24e
Revises: d5856d0e2f50
Create Date: 2026-07-27 00:29:53.454915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ad6aa0d24e'
down_revision: Union[str, Sequence[str], None] = 'd5856d0e2f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plugin_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_instances_organization_id'), 'connector_instances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_connector_instances_plugin_key'), 'connector_instances', ['plugin_key'], unique=False)
    op.create_table('response_action_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('plugin_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_action_instances_organization_id'), 'response_action_instances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_response_action_instances_plugin_key'), 'response_action_instances', ['plugin_key'], unique=False)
    op.add_column('proposed_actions', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('proposed_actions', sa.Column('execution_result', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposed_actions', 'execution_result')
    op.drop_column('proposed_actions', 'executed_at')
    op.drop_index(op.f('ix_response_action_instances_plugin_key'), table_name='response_action_instances')
    op.drop_index(op.f('ix_response_action_instances_organization_id'), table_name='response_action_instances')
    op.drop_table('response_action_instances')
    op.drop_index(op.f('ix_connector_instances_plugin_key'), table_name='connector_instances')
    op.drop_index(op.f('ix_connector_instances_organization_id'), table_name='connector_instances')
    op.drop_table('connector_instances')
    # ### end Alembic commands ###
