"""add analyst_feedback table

Revision ID: fe27ad01d1e6
Revises: c12e27eed126
Create Date: 2026-07-27 03:02:13.714570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe27ad01d1e6'
down_revision: Union[str, Sequence[str], None] = 'c12e27eed126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_feedback_agent_run_id'), 'analyst_feedback', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_analyst_feedback_incident_id'), 'analyst_feedback', ['incident_id'], unique=False)
    op.create_index(op.f('ix_analyst_feedback_organization_id'), 'analyst_feedback', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyst_feedback_organization_id'), table_name='analyst_feedback')
    op.drop_index(op.f('ix_analyst_feedback_incident_id'), table_name='analyst_feedback')
    op.drop_index(op.f('ix_analyst_feedback_agent_run_id'), table_name='analyst_feedback')
    op.drop_table('analyst_feedback')
    # ### end Alembic commands ###
